#Aayush Kumar Chaudhary
#23053767

#NumPy

# 1. Write a program to create a null vector of size 25 but the values from fifth to tenth elements are all 1

In [2]:
import numpy as np

vec = np.zeros(25)


vec[4:10] = 1

print(vec)


[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


# 2. Write a program to create a vector with values ranging from 5 to 20 & reverse it

In [3]:
import numpy as np

vec = np.arange(5, 21)

rev_vec = vec[::-1]

print("vec:", vec)
print("reversed vec: ", rev_vec)

vec: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
reversed vec:  [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]


# 3. Write a program to create a vector with 10 random values & sort first half ascending&secondhalfdescending.

In [9]:
import numpy as np

#ran_vec = np.random.rand(10)
ran_vec = np.random.randint(1,50,10)

first_asce = np.sort(ran_vec[:5])

last_desc = np.sort(ran_vec[5:])[:-1]

print(ran_vec)

print("first asce:",first_asce)
print("last desc:", last_desc)

[ 5 15  9 26 41 16 10 48 23 38]
first asce: [ 5  9 15 26 41]
last desc: [10 16 23 38]


# 4. Write a program to create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [23]:
import numpy as np

vec = np.linspace(0, 1, 12)[1:-1]

print(vec)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#5. Write a program to concatenate element-wise two arrays of string.


In [12]:
import numpy as np

arr1 = np.array([ "hello", "This"])
arr2 = np.array([ "hi", "That"])

result = np.char.add(arr1, " ")
result = np.char.add(result, arr2)

print("Concatenated array:")
print(result)


Concatenated array:
['hello hi' 'This That']


#6. Write a program to create a 4x3 array with random values & find out the minimum&maximumvalues.

In [16]:
import numpy as np

arr1= np.random.randint(1,50,(4,3))

print(arr1)
print("min value:", arr1.min())
print("max value:",arr1.max)


[[18  1 20]
 [ 4 38  4]
 [24 20 28]
 [19 38 21]]
min value: 1
max value: 38


#7. Write a program to create a 2D array with 1 on the border and 0 inside.

In [20]:
import numpy as np

arr1= np.random.randint(1,2,(4,3))

arr1[1:-1, 1:-1] = 0


print(arr1)



[[1 1 1]
 [1 0 1]
 [1 0 1]
 [1 1 1]]


#8. Write a program to create a 4x4 matrix with values 1,2,3,4 just below & above the diagonal, rest zeros.

In [27]:
import numpy as np

arr1 = np.zeros((4, 4), dtype=int)

values = [1, 2, 3, 4]

for i in range(4):
    if i < 3:
        arr1[i, i+1] = values[i]

for i in range(4):
    if i > 0:
        arr1[i, i-1] = values[i]

print(arr1)


[[0 1 0 0]
 [2 0 2 0]
 [0 3 0 3]
 [0 0 4 0]]


#.9. Write a program to extract all the contiguous 3x3 blocks from a random 10x10 matrix.

In [36]:
import numpy as np

arr1 = np.random.randint(1, 5, (10, 10))

blocks = []

for row in range(8):  # 10 - 3 + 1 = 8
    for col in range(8):
        arr = arr1[row:row+3, col:col+3]
        blocks.append(arr)

print("3x3 blocks:")
for index, arr in enumerate(blocks):
    print(f"Block {index + 1}:")
    print(arr)
    print()

print("Original array:")
print(arr1)


3x3 blocks:
Block 1:
[[3 3 1]
 [4 4 3]
 [2 2 3]]

Block 2:
[[3 1 4]
 [4 3 3]
 [2 3 2]]

Block 3:
[[1 4 1]
 [3 3 3]
 [3 2 2]]

Block 4:
[[4 1 4]
 [3 3 3]
 [2 2 3]]

Block 5:
[[1 4 2]
 [3 3 2]
 [2 3 4]]

Block 6:
[[4 2 3]
 [3 2 4]
 [3 4 2]]

Block 7:
[[2 3 1]
 [2 4 4]
 [4 2 4]]

Block 8:
[[3 1 3]
 [4 4 3]
 [2 4 4]]

Block 9:
[[4 4 3]
 [2 2 3]
 [1 1 2]]

Block 10:
[[4 3 3]
 [2 3 2]
 [1 2 1]]

Block 11:
[[3 3 3]
 [3 2 2]
 [2 1 2]]

Block 12:
[[3 3 3]
 [2 2 3]
 [1 2 2]]

Block 13:
[[3 3 2]
 [2 3 4]
 [2 2 2]]

Block 14:
[[3 2 4]
 [3 4 2]
 [2 2 1]]

Block 15:
[[2 4 4]
 [4 2 4]
 [2 1 4]]

Block 16:
[[4 4 3]
 [2 4 4]
 [1 4 3]]

Block 17:
[[2 2 3]
 [1 1 2]
 [2 2 2]]

Block 18:
[[2 3 2]
 [1 2 1]
 [2 2 3]]

Block 19:
[[3 2 2]
 [2 1 2]
 [2 3 3]]

Block 20:
[[2 2 3]
 [1 2 2]
 [3 3 1]]

Block 21:
[[2 3 4]
 [2 2 2]
 [3 1 1]]

Block 22:
[[3 4 2]
 [2 2 1]
 [1 1 3]]

Block 23:
[[4 2 4]
 [2 1 4]
 [1 3 4]]

Block 24:
[[2 4 4]
 [1 4 3]
 [3 4 3]]

Block 25:
[[1 1 2]
 [2 2 2]
 [1 2 2]]

Block 26:
[[1 2 1]
 [2

# 10. A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonalgoesfrom top right to bottom left.) Show by direct computation that if the matrix A


In [37]:
import numpy as np

A = np.array([
    [17, 24,  1,  8, 15],
    [23,  5,  7, 14, 16],
    [ 4,  6, 13, 20, 22],
    [10, 12, 19, 21,  3],
    [11, 18, 25,  2,  9]
])

row_sums = np.sum(A, axis=1)

col_sums = np.sum(A, axis=0)

main_diag = np.sum(np.diag(A))
other_diag = np.sum(np.diag(np.fliplr(A)))

all_sums = np.concatenate((row_sums, col_sums, [main_diag, other_diag]))

if np.max(all_sums) == np.min(all_sums):
    print("A is a magic square.")
    print("Magic sum =", np.max(all_sums))
else:
    print("A is NOT a magic square.")


A is a magic square.
Magic sum = 65
